from django.urls import path, include
from . import views
from . import views_constructor

urlpatterns = [
    path('', views.info_page_view, name='home'),
    path('admin-panel/', views.admin_panel_view, name='admin_panel'),
    path('api/roles/users/', views.get_users_by_role, name='get_users_by_role'),
    path('api/roles/add/', views.add_role, name='add_role'),
    path('api/roles/remove/', views.remove_role, name='remove_role'),
    path('api/users/create/', views.create_new_user, name='create_new_user'),
    path('broadcast/', views.broadcast_view, name='broadcast'),
    path('api/tournament/create/', views.create_tournament_api, name='create_tournament'),
    path('api/teams/add/', views.add_team_api, name='add_team'),
    path('api/teams/', views.get_teams_api, name='get_teams'),
    path('api/teams/delete/', views.delete_team_api, name='delete_team'),
    path('api/teams/upload-csv/', views.upload_teams_csv_api, name='upload_teams_csv'),
    path('api/fights/teams/', views.get_teams_for_select_api, name='get_teams_for_select'),
    path('api/fights/add/', views.add_fight_api, name='add_fight'),
    path('api/fights/list/', views.get_fights_list_api, name='get_fights_list'),
    path('api/fights/delete/', views.delete_fight_api, name='delete_fight'),
    path('api/teams/edit/', views.edit_team_api, name='edit_team'),
    path('api/fights/leagues/', views.get_leagues_api, name='get_leagues'),
    path('api/summary/', views.get_class_summary_api, name='get_class_summary'),
    path('api/olympiad/save/', views.save_olympiad_api, name='save_olympiad'),
    path('api/olympiad/list/', views.get_olympiad_api, name='get_olympiad_list'),
    path('api/schedule/add/', views.schedule_fight_api, name='schedule_fight'),
    path('api/fights/add_result/', views.add_fight_result_api, name='add_fight_result'),
    path('api/schedule/list/', views.get_schedule_api, name='get_schedule'),
    path('api/schedule/list_unended/', views.get_scheduled_fights_api, name='get_scheduled_fights'),
    path('api/fights/remove_result/', views.remove_fight_result_api, name='remove_fight_result'),
    path('api/schedule/upload-csv/', views.upload_schedule_csv_api, name='upload_schedule_csv'),
    path('api/olympiad/upload-csv/', views.upload_olympiad_csv_api, name='upload_olympiad_csv'),
    path('api/matches/upload-csv/', views.upload_matches_csv_api, name='upload_matches_csv'),
    path('api/export/<str:export_type>/', views.export_csv_api, name='export_csv'),
    path('api/constructor/tournaments/', views_constructor.get_tournaments_api, name='cons_tournaments'),
    path('api/constructor/simulate/', views_constructor.run_simulation_api, name='cons_simulate'),
    path('api/constructor/pairing/', views_constructor.generate_pairing_api, name='cons_pairing'),
    path('constructor/', views.constructor_page, name='constructor_page'),
    path('api/constructor/calc-tours/', views_constructor.calculate_tours_api, name='cons_calc_tours'),

    path('info/', views.info_page_view, name='info_page'),
    path('api/docs/upload/<str:doc_type>/', views.upload_tournament_doc_api, name='upload_doc'),
    path('api/faq/add/', views.add_faq_api, name='add_faq'),
    path('api/faq/delete/', views.delete_faq_api, name='delete_faq'),
]