# Generated by Django 6.0.2 on 2026-03-01 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=255, verbose_name='Рабочее название')),
                ('child_name', models.CharField(max_length=255, verbose_name='Детское название')),
                ('players_quantity', models.CharField(max_length=50, verbose_name='Количество игроков')),
                ('komol_points', models.IntegerField(blank=True, null=True, verbose_name='Баллы на комоле')),
                ('current_points', models.IntegerField(default=0, verbose_name='Текущие очки')),
                ('league', models.CharField(blank=True, max_length=100, null=True, verbose_name='Лига')),
                ('school_class', models.IntegerField(blank=True, null=True, verbose_name='Класс')),
                ('in_league_number', models.IntegerField(blank=True, null=True, verbose_name='Номер внутри лиги')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_number', models.IntegerField(verbose_name='Номер турнира')),
                ('start_date', models.DateField(verbose_name='Дата старта')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
            },
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_one_points', models.IntegerField(blank=True, null=True, verbose_name='Очки команды 1')),
                ('team_two_points', models.IntegerField(blank=True, null=True, verbose_name='Очки команды 2')),
                ('place', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('value_day', models.DateField(verbose_name='Дата проведения')),
                ('tour_number', models.IntegerField(verbose_name='Номер тура')),
                ('ended', models.BooleanField(default=False, verbose_name='Закончился ли бой')),
                ('team_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights_as_team_one', to='core.team', verbose_name='Команда 1')),
                ('team_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights_as_team_two', to='core.team', verbose_name='Команда 2')),
            ],
            options={
                'verbose_name': 'Бой',
                'verbose_name_plural': 'Бои',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.tournament', verbose_name='Турнир'),
        ),
    ]
