# Generated by Django 6.0.2 on 2026-03-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_team_tournament_fight_team_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='komol_minuses',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минусы на комоле'),
        ),
    ]
