# Generated by Django 6.0.2 on 2026-03-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_team_komol_minuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='players_quantity',
            field=models.CharField(max_length=50, verbose_name='Количество участников'),
        ),
    ]
