# Generated by Django 6.0.2 on 2026-03-29 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_team_players_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='players_quantity',
            field=models.IntegerField(blank=True, verbose_name='Количество участников'),
        ),
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plus_count', models.IntegerField(default=0)),
                ('minus_count', models.IntegerField(default=0)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='olympiad', to='core.team')),
            ],
        ),
    ]
