# Generated by Django 6.0.2 on 2026-04-05 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_team_players_quantity_olympiad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fight',
            options={},
        ),
        migrations.AddField(
            model_name='fight',
            name='fight_time',
            field=models.TimeField(default='23:59'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fight',
            name='judge_first',
            field=models.CharField(default='23:59', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fight',
            name='judge_second',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fight',
            name='solution_place',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fight',
            name='solution_ts',
            field=models.TimeField(default='23:59'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fight',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fight',
            name='place',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fight',
            name='team_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights_team_one', to='core.team'),
        ),
        migrations.AlterField(
            model_name='fight',
            name='team_one_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fight',
            name='team_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights_team_two', to='core.team'),
        ),
        migrations.AlterField(
            model_name='fight',
            name='team_two_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fight',
            name='tour_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fight',
            name='value_day',
            field=models.DateField(),
        ),
    ]
