# Generated by Django 6.0.2 on 2026-04-05 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_fight_options_fight_fight_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='fight_time',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AlterField(
            model_name='fight',
            name='judge_first',
            field=models.CharField(default='Не назначен', max_length=255),
        ),
        migrations.AlterField(
            model_name='fight',
            name='place',
            field=models.CharField(default='ТВА', max_length=255),
        ),
        migrations.AlterField(
            model_name='fight',
            name='solution_place',
            field=models.CharField(default='ТВА', max_length=255),
        ),
        migrations.AlterField(
            model_name='fight',
            name='solution_ts',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AlterField(
            model_name='fight',
            name='tour_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fight',
            name='value_day',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
