# Generated by Django 6.0.2 on 2026-06-06 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_fight_fight_time_alter_fight_judge_first_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='info_letter_file',
            field=models.FileField(blank=True, null=True, upload_to='tournament_docs/', verbose_name='Информационное письмо'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rules_file',
            field=models.FileField(blank=True, null=True, upload_to='tournament_docs/', verbose_name='Свод правил'),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Частый вопрос',
                'verbose_name_plural': 'Частые вопросы',
            },
        ),
    ]
